version: '3'
services:
  app:
    image: mynodeapp
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123456789'
      MYSQL_DATABASE: fastifydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
