name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      # 1. Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify your Node.js version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run npm install in the frontend folder if applicable
      - name: npm install in frontend
        working-directory: ./front_bdd_creator  # Adjust if your frontend directory is different
        run: npm install

      # 5. Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # 6. Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # 7. Start Docker Compose
      - name: Start Docker Compose
        working-directory: ./
        run: docker-compose up -d

      # 8. Run tests
      - name: Run tests
        run: |
          sleep 10  # Wait for the services to be ready
          npm test  # Run your tests
